spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  profiles:
    active: dev

# 配置日志
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:    # 指定mybatis全局配置文件中相关配置（就是mybatis-config.xml）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开启默认日志输出

  global-config:
    db-config:
      logic-delete-field: flag    # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1       # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0   # 逻辑未删除值(默认为 0)
# 服务端口(可以按自己的配置)
server:
  port: 9000
